# Generated by Django 2.2 on 2021-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
