# Generated by Django 3.1.7 on 2021-04-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
